### ISSUE TITLE
The zeo_client should inherit all values of the [instance] part

### ISSUE THREAD

**Issue by erral** [eea/eea.docker.plone#10]
As a follow-up of https://github.com/eea/eea.docker.gitflow/pull/6

When creating the `zeo_client` part in buildout, its options are not based on the `instance` part:

https://github.com/eea/eea.docker.plone/blob/master/src/plone/eea.cfg#L247-L253

This means that if one sets some environment-vars in the `[instance]` part, such as the default `zope_i18n_compile_mo_files` that is set by the unified installer when creates the basic buildout file, are not passed to the zeo_client part and thus it can't compile the po files into mo:

https://github.com/plone/Installers-UnifiedInstaller/blob/master/base_skeleton/base.cfg#L50-L51

Moreover, to make this fully functional, the `gettext` package should also be installed in the underlying OS when creating the base images, adding it to the relevant runDeps in Dockerfile.

**Comment by erral** [comment]
I have debugged this the following way:

- start a container with this docker image:
```bash
$ docker run --name my-plone -p 8080:8080 eeacms/plone
```
- enter to the running container:
```bash
$ docker exec -it my-plone bash
```
- inspect and compare the following files:
```bash
$ more /plone/instance/parts/instance/etc/zope.conf
```
```
...
<environment>
    zope_i18n_compile_mo_files true
PYTHON_EGG_CACHE /plone/instance/var/.python-eggs
CHAMELEON_CACHE /data/cache
</environment>

...
```
```bash
$ more /plone/instance/parts/zeo_client/etc/zope.conf
```
```
...
<environment>
MEMCACHE_SERVER memcached:11211
ZC_ASYNC_UUID /plone/instance/var/zeo_client-uuid.txt
CHAMELEON_CACHE /plone/instance/var/cache
</environment>

...
```

As you can see the items in the `instance` instance are not the same as in the `zeo_client` instance

**Comment by alecghica** [comment]
Tracked under https://taskman.eionet.europa.eu/issues/160898

**Comment by Petchesi-Iulian** [comment]
#17 should fix this issue, what I get when I enter the container:

```
root@4ad12cbe7493:/plone/instance# more /plone/instance/parts/zeo_client/etc/zope.conf
<environment>
zope_i18n_compile_mo_files true
PYTHON_EGG_CACHE /plone/instance/var/.python-eggs
MEMCACHE_SERVER memcached:11211
ZC_ASYNC_UUID /plone/instance/var/zeo_client-uuid.txt
CHAMELEON_CACHE /data/cache
</environment>
```
